CREATE TABLE IF NOT EXISTS `db`.`USERS` (

    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CONFIRMED BOOLEAN DEFAULT false
);

INSERT INTO `db`.`USERS` (EMAIL, CONFIRMED) VALUES ('john@gmail.com', true);
INSERT INTO `db`.`USERS` (EMAIL, CONFIRMED) VALUES ('benjamin@gmail.com', false);